services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: renatoguii
      POSTGRES_PASSWORD: 153422
      POSTGRES_DB: faturaflow
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - faturaflownetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - faturaflownetwork

  faturaflowapi:
#    build:
#      dockerfile: Dockerfile
#      context: ./faturaflowapi
    image: renatoguii/faturaflowapi:latest
    container_name: faturaflowapi
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - faturaflownetwork
    environment:
      - "POSTGRES_HOST=db"

  faturaflowweb:
#    build:
#      dockerfile: Dockerfile
#      context: ./faturaflow
    image: renatoguii/faturaflowweb:latest  # Usando a imagem do Docker Hub
    container_name: faturaflowweb
    depends_on:
      - faturaflowapi
    ports:
      - "3000:3000"
    networks:
      - faturaflownetwork
    expose:
      - 3000

networks:
  faturaflownetwork:
    driver: bridge